trigger:
- devops

pool:
  vmImage: 'macOS-latest'

variables:
  APP_IDENTIFIER: 'com.dev.yavia.com'
  APPLE_ID: '5B43L7AV6M'
  ASC_APP_ID: '6746633933'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g expo-cli eas-cli
  displayName: 'Install Expo CLI'

- script: |
    cd cutesy-finance
    npm ci
  displayName: 'Install dependencies'
   

- script: |
    cd cutesy-finance
    eas build --platform ios --non-interactive --profile production
  env:
    EXPO_TOKEN: $(EXPO_TOKEN)


- script: |
    cd cutesy-finance
    eas submit --platform ios --non-interactive \
      --latest \
      --apple-id $(APPLE_ID) \
      --asc-app-id $(ASC_APP_ID)
  env:
    EXPO_TOKEN: $(EXPO_TOKEN)
  displayName: 'Submit to App Store'
