trigger:
- devopsandroid

pool:
  vmImage: 'ubuntu-latest'

variables:
  APP_IDENTIFIER: 'com.dev.yavia.com'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g expo-cli eas-cli
  displayName: 'Install Expo CLI'

- script: |
    cd cutesy-finance
    npm ci
  displayName: 'Install dependencies'

- script: |
    cd cutesy-finance
    eas build --platform android --non-interactive --profile production
  env:
    EXPO_TOKEN: $(EXPO_TOKEN)
  displayName: 'Build Android app'

- script: |
    cd cutesy-finance
    eas submit --platform android --non-interactive \
      --latest \
      --key $(PLAY_STORE_SERVICE_ACCOUNT_JSON)
  env:
    EXPO_TOKEN: $(EXPO_TOKEN)
  displayName: 'Submit to Play Store'
