export const DocuVaultTypeEnum = Object.freeze({
  ProfilePicture: 1,
  Passport: 2,
  DrivingLicense: 3,
  UtilityBill: 4,
  BankStatement: 5,
  Payslip: 6,
  Creditreport: 7,
  P60: 8,
  SA302: 9,
  Savings: 10,
  TaxOverview: 11,
  MortgageStatement: 12,
  FactFind: 13,
  BenefitsInformation: 14,
  Miscellaneous: 15,
  BusinessBankStatement: 16,
  TaxCalculation: 17,
  FullBusinessAccounts: 18,
  TenancyAgreement: 19,
});
