export const ProfilingOptionEnum = Object.freeze({
  WithoutIncomeProtection: 1,
  WithoutLifeInsurance: 2,
  WithoutLifeAndCriticalIlnessInsurance: 3,
  WithoutHomeInsurance: 4,
  WithoutMortgageProtection: 5,
  WithoutFamilyIncomeBenefits: 6,
  WithoutHealth: 7,
  SelfEmployedMortgageNoProtection: 8,
  SelfEmployedMortgageLifeCINoIP: 9,
  SelfEmployedMortgageLifeNoCINoIP: 10,
  SelfEmployedMortgageCINoLifeNoIP: 11,
  SelfEmployedMortgageCIIPNoLife: 12,
  SelfEmployedMortgageIPNoLifeNoCI: 13,
  EmployedMortgageNoProtection: 14,
  EmployedMortgageHasLifeNoCriticalIlness: 15,
  EmployedMortgageHasCriticalIlnessNoLife: 16,
  PensionNoGoals: 17,
  PensionOrInvestmentNoProtection: 18,
  PensionOrInvestmentLifeNoIP: 19,
  PensionOrInvestmentIPNoLife: 20,
  HightNetWorthNoWillNorTrust: 21,
});
